spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: src/main/resource/ddl.sql